### ISSUE TITLE
Having Trouble Setting Up

### ISSUE THREAD

**Issue by emre-k1** [Azure-Functions/jekyll-blog-comments#13]
Hello,
I'm a total newbie in web programming and I'm having trouble setting this up to work with my jekyll blog. I've barely been able to follow the steps so far and in step 4, when I try to "create a function app with source files deployed from the specified GitHub repo", I get this error message:
 
> Link to git repository failed due to error 'Deployment failed. Correlation ID: 931048d0-11ce-4b01-a793-7737d6a9f0e4. Operation failed with status: 200. Details: Resource state Failed'

Any help would be greatly appreciated. And I'm sorry if this isn't the right place to ask. Thanks!

-Emre.

**Comment by damieng** [comment]
If you check out the logs you should see more information - that correlation ID might point to something more?

I've not seen this error before and all I could find was this thread with a similar issue on another function that also didn't get a solid answer https://github.com/MicrosoftDocs/azure-docs/issues/20042

I'd try removing it and starting again and also make sure it's **v1** - the code in this is not compatible with v2 as it's a very different environment.  (I posted about the breaking differences at https://damieng.com/blog/2018/03/29/azure-functions-differences-v1-v2 )

**Comment by emre-k1** [comment]
Hello again Damien,
Thanks a lot for your help. My functionapp version turned out to be v2 indeed, and when I switched to v1, deployment issue seems to have been fixed. 

However, I still can't get the comments to work. When I try to leave a comment on my blog, it redirects to an error page with a message saying: 

> /api/PostComment' not found.

I'm not sure what might be wrong here, but I have 2 elementary questions to make sure I'm not doing it all wrong:

1. My blog isn't hosted on GitHub. Is it still possible to get this to work with a custom domain & hosting?
2. I actually don't have my site up yet and I'm testing this on my local computer. Whenever I'm asked to enter my website in azure functionapp, I'm just using "http://localhost:4000". Could this be a problem?

I'm also adding my functionapp settings & deployment pages. Any ideas where I'm going wrong? Thanks again and very sorry for the newbie questions.

-Emre

![Screen Shot 2019-03-22 at 18 42 32](https://user-images.githubusercontent.com/39337114/54835629-969a0f00-4cd3-11e9-971b-946920fd9fc6.png)

![Screen Shot 2019-03-22 at 18 43 45](https://user-images.githubusercontent.com/39337114/54835630-969a0f00-4cd3-11e9-985c-d1f2e4f71ff7.png)

**Comment by damieng** [comment]
It will work with any hosting providing the underlying source for your blog is hosted on GitHub.

What's the address bar say when you see the 404 not found for /api/postComment?

**Comment by emre-k1** [comment]
It says: 

> http://localhost:4000/api/PostComment

**Comment by damieng** [comment]
Ah, I see.  So what's happening here is your form post isn't posting to your Azure function but is instead posting back to your local dev box.

If you're using my Jekyll templates to render the form post then you'll need to change the comments receiver setting in your _config.yml as described at https://github.com/damieng/jekyll-blog-comments#configuring-jekyll-for-the-templates

If you're using your own form post system then you'll need to make sure the form's action attribute is pointing to your Azure function.

**Comment by emre-k1** [comment]
Ok, I've updated that setting with the URL of my functionapp. Hopefully it's correct:

`receiver: https://zntest1.azurewebsites.net/api/PostComment}}`

This way, I get a blank page when I submit a comment. I also tried removing the double braces at the end (not sure if they are needed or not) and in that case I get a new error page:

![Screen Shot 2019-03-22 at 20 17 45](https://user-images.githubusercontent.com/39337114/54841269-fc8c9380-4cdf-11e9-9fcd-5054c2e47540.png)

I tried looking for that error in azure portal logs but I'm not sure where to look and I couldn't find anything.

**Comment by damieng** [comment]
It should not have those `}}` at the end.

I tried posting to your endpoint with the following values and it returned an OK (it would be a 302 redirect with the redirect parameter specified)

![image](https://user-images.githubusercontent.com/118951/54849381-5d48ab80-4ca1-11e9-98da-710cad2104cd.png)

If you are using the https://github.com/damieng/jekyll-blog-comments/tree/master/jekyll/_includes for your form make sure you haven't inadvertently broken any of the parameters etc.  If you are doing your own form you'll need to make sure it matches these names for the post.

**Comment by emre-k1** [comment]
Hey Damien, my repository seems to be receiving comments in form of pull requests, so I guess it's working now! 
I still have a lot to figure out, but thanks a lot for your help.

-Emre.

**Comment by emre-k1** [comment]
Hello again,
Back with another newbie question. So, I've been trying to display a list of recent comments but I haven't been able to get it work so far. All I've managed to get is a form of raw data with this code:

```
  <ul>
    {% for comment in site.data.comments %}
      <li>{{comment}}</li>
    {% endfor %}
  </ul>
```

I can't access individual details like commenter name, etc. Any pointers would be appreciated.

**Comment by damieng** [comment]
I have a seperate GitHub repo for the actual display of the comments including templates etc. 

It is at https://github.com/damieng/jekyll-blog-comments and includes three files you can use to get going and the configuration steps necessary in Jekyll :)

**Comment by emre-k1** [comment]
Hey Damien,
I have those 3 files included in my blog and I can display the comments below each post. That part works great. However what I want is like a seperate section on my index page that displays all the recent comments from the whole page.

**Comment by damieng** [comment]
I think what's happening in your sample is that by going over site.data.comments the "comment" isn't an individual comment but is rather an array of comments for a specific post.  I'll see if I can knock up a most recent X comments loop and put it as an example on the other repo.

**Comment by emre-k1** [comment]
That would be fantastic. Thanks again for your help!

**Comment by damieng** [comment]
Snippet of how to do latest comments now available at https://github.com/damieng/jekyll-blog-comments/blob/master/README.md#optional-latest-comments-snippet

**Comment by emre-k1** [comment]
Hi again Damien,
I figured out the cause of the error I've posted before. It seems to be a result of inputting random characters in the e-mail field. When I enter it in "abc@xyz format", it works correctly. I'm not sure if it's something I've broken or not, but I just wanted to let you know.

> ![Screen Shot 2019-03-22 at 20 17 45](https://user-images.githubusercontent.com/39337114/54841269-fc8c9380-4cdf-11e9-9fcd-5054c2e47540.png)
>

**Comment by damieng** [comment]
Hmm, there is email validation in the code. I'll check it out when I have some time.

**Comment by emre-k1** [comment]
Hi, I'm back with a new problem.

My comments were working nicely on my local computer but they've stopped working after I've got my website running online. It returns this error when I try to send a comment:

> This Jekyll comments receiever does not handle forms for '$http://localhost:4000'. You should point to your own instance.

I've updated the "CommentWebsiteUrl" setting in the azure function with my current web address, so I'm not sure where I'm going wrong. Any help would be appreciated.

-Emre

**Comment by damieng** [comment]
Whenever you go from one page to another your browser sends a http referrer to say where it came from.

To stop spam/abuse the Azure function has that CommentWebsiteUrl parameter to make sure only your web site is allowed to post to it.

When you run the site locally and post comments it's not coming from your real online url/web site any more but from localhost and the function notices it doesn't match and rejects it.

If you need to be able to run the real site and your local computer copy together with posting comments you'll need to either modify the function to allow two url's to be specified as referrers or run a second copy of the azure function.

To be honest though if it's working fine online now there's no need to call it from localhost.

**Comment by emre-k1** [comment]
Hey Damien,

I think my description was inaccurate. Because it's not working online either. I'm getting that error when I try to leave a comment online. But my Azure Function CommentWebsiteUrl parameter is configured with my current web address. So I'm not sure what's wrong.

If you want to check it out, here's a post on my blog (Which is a total newbie project!): [http://zindanname.com/temel/frp-nedir.html](url)

**Comment by damieng** [comment]
There are two hidden form values that the jekyll code uses which are incorrectly set on your site:

```html
<input name="redirect" type="hidden" value="http://localhost:4000/thanks">
<input name="comment-site" type="hidden" value="http://localhost:4000">
```

The default template picks these up from site.url in your Jekyll so I suspect your _config.yml is wrong. You probably have:

```yml
url: http://localhost:4000
```

You should have:

```yml
url: http://zindanname.com
```

**Comment by emre-k1** [comment]
My site.url variable refuses to work for some reason so I had to edit those 2 parameters manually. But it's fixed now! Many thanks again :-)

**Comment by emre-k1** [comment]
Hi Damien,

I'm sure this isn't the right place to ask but I haven't been able to find a way to do this. 

So, my question is this: When someone leaves a comment on my site, I get a pull request on the Github repository, right? Is there a way to be notified of this pull request automatically, so that I can moderate the comment? Or do I have to check Github periodically to see if there are any new comments?

Cheers!
-Emre.

**Comment by damieng** [comment]
Normally GitHub can send you emails about pull requests but it doesn't do that if you created the pull request yourself - including via an API :(

The two options are either:

1. Create another account and use the token from that so GitHub sees it as coming somebody else and emails you (make sure you give that account rights to your repo).  e.g. you could create a "emre-k1-blog-comments" account.

2. Add an email responder to your fork of the azure function that fires off an email to you. https://cloudops2pm.com/2017/08/10/send-email-through-azure-function-triggered-by-queue/ has some example code

**Comment by emre-k1** [comment]
Ok, I feel like I can accomplish the 1st method. Thanks!
